Workflow for v2024
taiyme/misskey pull request #213
Opened 2024-05-07 15:28 UTC by cffnpwr

## What
Github ActionsのWorkflowを調整
- 対象ブランチを`develop`→`taiyme`に変更
- 不要だと思われるworkflowを削除
- Docker Imageビルドの共通化

## Why

## Additional info (optional)

## Checklist
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If possible) Add tests

2024-05-07 15:40 UTC, taiyme commented
これもしかしたら ee094e15a482367a493b32e1276dd9285eb047e5 をrevertして、git merge --no-ff origin/taiyme もしくは git rebase origin/taiyme する必要がある？

2024-05-07 15:46 UTC, cffnpwr commented
なんとかなったっぽいな

2024-05-08 05:21 UTC, taiyme requested changes

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/check-spdx-license-id.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/check_copyright_year.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/dockle.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/lint.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/release.yaml
ここで .yaml を採用するのであれば、他のYAMLファイルも .yaml にしたい

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/test-backend.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/test-frontend.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on .github/workflows/test-production.yml
>        - master
```suggestion
```

2024-05-08 05:21 UTC, taiyme commented on docker-compose_example.yml
> +    image: ghcr.io/taiyme/misskey:12.119.2-taiyme-v1.2.0
ここ情報が古いのもアレなので、どうしようかなーと思ってる
即座にリリースすればいい話だけど

2024-05-08 10:15 UTC, cffnpwr commented on docker-compose_example.yml
> +    image: ghcr.io/taiyme/misskey:12.119.2-taiyme-v1.2.0
`build`と`image`を書くとリモートリポジトリにイメージがない場合にビルドを行なうようになるので、`image`をダミーに指定した
これはリリース時に書き換わる

2024-05-08 10:33 UTC, taiyme approved these changes

2024-05-08 10:34 UTC, merged